/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.saga.sync.quicksynccontroller.ui;

import java.awt.Frame;
import javax.swing.JDialog;
import net.saga.sync.quicksynccontroller.repository.DeviceRepository;
import net.saga.sync.quicksynccontroller.repository.StartupFactory;
import net.saga.sync.quicksynccontroller.vo.Device;

/**
 *
 * @author summers
 */
public class DeviceEntry extends javax.swing.JPanel {
    private Device device;

    /**
     * Creates new form DeviceEntry
     */
    public DeviceEntry() {
        initComponents();
    }

    public DeviceEntry(Device device) {
        initComponents();
        this.device = device;
        this.deviceName.setText(device.deviceName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceName = new javax.swing.JLabel();
        scoreButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 36));
        setMinimumSize(new java.awt.Dimension(220, 36));
        setPreferredSize(new java.awt.Dimension(220, 36));

        deviceName.setText("deviceName");

        scoreButton.setText("Edit Score");
        scoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deviceName, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviceName)
                    .addComponent(scoreButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreButtonActionPerformed
        final JDialog dialog = new JDialog((Frame)null, "Edit Score", false);
        EditScore editScore = new EditScore(device, dialog, new DeviceRepository(StartupFactory.getDb()));
        dialog.setContentPane(editScore);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_scoreButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deviceName;
    private javax.swing.JButton scoreButton;
    // End of variables declaration//GEN-END:variables
}
