/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.saga.sync.quicksynccontroller.ui;

import net.saga.sync.quicksynccontroller.vo.Device;

/**
 *
 * @author summers
 */
public class DeviceEntry extends javax.swing.JPanel {

    /**
     * Creates new form DeviceEntry
     */
    public DeviceEntry() {
        initComponents();
    }

    public DeviceEntry(Device device) {
        initComponents();
        this.deviceName.setText(device.deviceName);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceName = new javax.swing.JLabel();
        scoreButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 36));
        setMinimumSize(new java.awt.Dimension(220, 36));
        setPreferredSize(new java.awt.Dimension(220, 36));

        deviceName.setText("deviceName");

        scoreButton.setText("Edit Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deviceName, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviceName)
                    .addComponent(scoreButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deviceName;
    private javax.swing.JButton scoreButton;
    // End of variables declaration//GEN-END:variables
}
